FROM jupyter/pyspark-notebook:spark-3.5.0

# Instalar dependencias adicionales para el proyecto
RUN pip install --no-cache-dir \
    vaderSentiment \
    boto3 \
    psycopg2-binary \
    python-dotenv
